### ISSUE TITLE
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

### ISSUE THREAD

**Issue by vieirafrancisco** [vieirafrancisco/pq#1]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\users\francisco\appdata\local\programs\python\python39\lib\threading.py", line 950, in _bootstrap_inner
DEBUG:urllib3.connectionpool:https://revistaquem.globo.com:443 "GET /QUEM-News/noticia/2020/12/nasce-raika-filha-de-alok-e-romana-novais.html HTTP/1.1" 200 None
    self.run()
  File "c:\users\francisco\appdata\local\programs\python\python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Francisco\Documents\github\pq\pq\worker.py", line 15, in run
    job.run()
  File "C:\Users\Francisco\Documents\github\pq\pq\job.py", line 8, in run
    self.callback(*self.args, **self.kwargs)
  File "C:\Users\Francisco\Documents\github\pq\task.py", line 18, in save_site_article
    text = get_site_text(url)
  File "C:\Users\Francisco\Documents\github\pq\task.py", line 7, in get_site_text
    soup = Soup(html.text, "lxml")
  File "C:\Users\Francisco\Documents\github\pq\venv\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
Exception in thread Thread-2:
Traceback (most recent call last):
  File "c:\users\francisco\appdata\local\programs\python\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\users\francisco\appdata\local\programs\python\python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Francisco\Documents\github\pq\pq\worker.py", line 15, in run
    job.run()
  File "C:\Users\Francisco\Documents\github\pq\pq\job.py", line 8, in run
    self.callback(*self.args, **self.kwargs)
  File "C:\Users\Francisco\Documents\github\pq\task.py", line 18, in save_site_article
    text = get_site_text(url)
  File "C:\Users\Francisco\Documents\github\pq\task.py", line 7, in get_site_text
    soup = Soup(html.text, "lxml")
  File "C:\Users\Francisco\Documents\github\pq\venv\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by vieirafrancisco** [comment]
`pip install lxml`
